export const PERMISSIONS = {

    CAR_TAB_ACCESS : 'vehicles.access',
    CAR_CREATE     : 'vehicles.create',
    CAR_UPDATE  : 'vehicles.edit',
    CAR_DELETE  : 'vehicles.delete',
    CAR_FEATURE : 'vehicles.feature',
    CUSTOMER_TAB_ACCESS : 'customers.access',
    CUSTOMER_CREATE : 'customers.create',
    CUSTOMER_UPDATE : 'customers.edit',
    CUSTOMER_DELETE : 'customers.delete',
    SUPPLIER_TAB_ACCESS : 'suppliers.access',
    SUPPLIER_CREATE : 'suppliers.create',
    SUPPLIER_UPDATE : 'suppliers.edit',
    SUPPLIER_DELETE : 'suppliers.delete',
    USER_TAB_ACCESS : 'users.access',
    ROLE_TAB_ACCESS : 'roles.access',
    PERMISSIONS_TAB_ACCESS : 'permissions.access',
    ANALYTICS_TAB_ACCESS : 'analytics.access',
    PROFILE_TAB_ACCESS : 'profile.access',
    DASHBOARD_TAB_ACCESS : 'dashboard.access',
    SETTINGS_TAB_ACCESS : 'settings.access',
    NOTIFICATIONS_TAB_ACCESS : 'notification.access',

}